### ISSUE TITLE
Both IOCs defined here have the same PREFIX

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lcls-plc-lfe-vac#21]
https://github.com/pcdshub/lcls-plc-lfe-vac/blob/1dfd613beb112495a283acca0d9b53ec4ac7a86f/plc_lfe_vac/iocBoot/ioc-plc-lfe-vac/Makefile#L12
https://github.com/pcdshub/lcls-plc-lfe-vac/blob/1dfd613beb112495a283acca0d9b53ec4ac7a86f/plc_lfe_vac/iocBoot/ioc-plc-lfe-vac-fs/Makefile#L12

This causes issues in the network and also spams the gateway logs (which is where I noticed this)

**Comment by slacAdpai** [comment]
Thank you for finding this. I'll get on it now!

**Comment by slacAdpai** [comment]
closed in #22
