### ISSUE TITLE
FB log handler is borken

### ISSUE THREAD

**Issue by slacAdpai** [pcdshub/lcls-plc-lfe-vac#8]
when log handler is built, the plc starts continuously adding errors.

![image](https://user-images.githubusercontent.com/42284230/75934910-a94d1b80-5e32-11ea-8763-d1aa2a06be2f.png)
 30 seconds later

![image](https://user-images.githubusercontent.com/42284230/75934934-b833ce00-5e32-11ea-81cd-1be6b2c2f214.png)

**Comment by klauer** [comment]
Need to install the TCP/IP library (TF6310) on the PLC, as @slacAWallace had hinted at in the PR #6)

https://infosys.beckhoff.com/english.php?content=../content/1033/tf6310_tc3_tcpip/18014398593618827.html&id=

**Comment by slacAWallace** [comment]
@slacAdpai Please take a look at this [page](https://confluence.slac.stanford.edu/display/L2SI/Logging+System) for details on getting this working.
